name: Build
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.getname.outputs.NAME }}
      icon: ${{ steps.getname.outputs.ICON }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install zip
        run: sudo apt-get install -y zip jq
      - id: getname
        run: |
          echo "NAME=$(cat info.json | jq '.id' | tr -d '"')" >> "$GITHUB_OUTPUT"
          echo "ICON=$(cat info.json | jq '.icon' | tr -d '"')" >> "$GITHUB_OUTPUT"
  build-for-windows:
    needs: check
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
        target: [x86_64-pc-windows-msvc]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
      - name: install toolchain
        run: |
          rustup target add ${{ matrix.target }}
          rustup toolchain install --force-non-host stable-${{ matrix.target }}
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Download PaddleOCR-json
        run: curl https://github.com/hiroi-sora/PaddleOCR-json/releases/download/v1.3.0/PaddleOCR-json_v.1.3.0.7z -o PaddleOCR-json_v.1.3.0.7z
      - name: extract-7z-action
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: PaddleOCR-json_v.1.3.0.7z
          pathTarget: PPOCR/PaddleOCR-json_v.1.3.0
      - name: Rename
        run: move target/${{ matrix.target }}/release/plugin.dll ./plugin.dll
      - uses: vimtor/action-zip@v1
        with:
          files: info.json ${{needs.check.outputs.icon}} plugin.dll PPOCR
          dest: ${{needs.check.outputs.name}}.potext
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: "*.potext"
          if-no-files-found: error
      - name: Wrap
        if: startsWith(github.ref, 'refs/tags')
        uses: vimtor/action-zip@v1
        with:
          files: ${{needs.check.outputs.name}}.potext
          dest: ${{ matrix.target }}.zip
      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.TOKEN }}
          files: ${{ matrix.target }}.zip
